# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Create_Points
                                 A QGIS plugin
 The plugin creates points from polylines
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2022-06-30
        copyright            : (C) 2022 by Houssem Benhmid
        email                : houssem.benhmid@circet.de
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Houssem Benhmid'
__date__ = '2022-06-30'
__copyright__ = '(C) 2022 by Houssem Benhmid'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Create_Points class from file Create_Points.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .create_points_processing import Create_PointsPlugin
    return Create_PointsPlugin(iface)
